// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxiFs-XVM3XpVYFtT1IUxm2oCxOhmHbo',
    appId: '1:788886365013:web:f68be2ad6f15c8749b05dc',
    messagingSenderId: '788886365013',
    projectId: 'for-eve-6ecbc',
    authDomain: 'for-eve-6ecbc.firebaseapp.com',
    storageBucket: 'for-eve-6ecbc.appspot.com',
    measurementId: 'G-SLV07WY3D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7_vX9oh7cnVClBp_fpVyRyovtXzD4Ec',
    appId: '1:788886365013:android:036edd0d8a13badd9b05dc',
    messagingSenderId: '788886365013',
    projectId: 'for-eve-6ecbc',
    storageBucket: 'for-eve-6ecbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGkBRTHKAJ-IZNMmapIJQ7YlTp8JNgio4',
    appId: '1:788886365013:ios:a4f57a5c03de7de29b05dc',
    messagingSenderId: '788886365013',
    projectId: 'for-eve-6ecbc',
    storageBucket: 'for-eve-6ecbc.appspot.com',
    iosClientId: '788886365013-r4uelvdivoqm58f51ueitm985rumqild.apps.googleusercontent.com',
    iosBundleId: 'com.example.forEve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGkBRTHKAJ-IZNMmapIJQ7YlTp8JNgio4',
    appId: '1:788886365013:ios:5e739ed640db4e089b05dc',
    messagingSenderId: '788886365013',
    projectId: 'for-eve-6ecbc',
    storageBucket: 'for-eve-6ecbc.appspot.com',
    iosClientId: '788886365013-veup9b5cp4vmc9ue4e6gidrveab11hki.apps.googleusercontent.com',
    iosBundleId: 'com.example.forEve.RunnerTests',
  );
}
